load("@prelude//android:android_toolchain.bzl", "GenruleToolchainInfo")

def _android_genrule_toolchain_impl(_ctx):
    return [
        AndroidPlatformInfo(),
        AndroidToolchainInfo()
    ]

android_genrule_toolchain = rule(
    impl = _android_genrule_toolchain_impl,
    attrs = {},
    is_toolchain_rule = True,
)


android_genrule_toolchain(
    name = "android",
    visibility = ["PUBLIC"],
)
