load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("toolchains.bzl", "android_toolchain", "dex_toolchain", "java_toolchain", "kotlin_toolchain", "java_test_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")


android_toolchain(
    name = "android",
    visibility = ["PUBLIC"]
)

java_toolchain(
    name = "java",
    visibility = ["PUBLIC"]
)

dex_toolchain(
    name = "dex",
    visibility = ["PUBLIC"]
)

kotlin_toolchain(
    name = "kotlin",
    visibility = ["PUBLIC"]
)

java_test_toolchain(
    name = "java_test",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)
