java_test(
        name = "traversals",
        srcs = glob("*.java"),
        deps = [
             "//java/io/ajarara/traversals:traversals",
             "//java/io/ajarara/utils:utils",
            "//:junit",
        ],
)
