plugin_repo(
  name = "java",
  revision = "v0.4.4",
  plugin = "java-rules",
  owner = "please-build",
)
plugin_repo(
  name = "cc",
  revision = "v0.4.0",
  plugin = "cc-rules",
  owner = "please-build",
)
