kotlin_binary(
    name = "kotdep",
    srcs = glob(['*.kt']),
    deps = [ "//java/io/ajarara/javakotdep:javakotdep" ],
    visibility = ["PUBLIC"],
    main_class = "io.ajarara.kotdep.ExampleKt",
)

