java_library(
    name = "example",
    srcs = glob(['*.java']),
    deps = [
        "//java/io/ajarara/dependency:dependency",
        "//java/io/ajarara/dep2:dep2",
    ],
    visibility = ["PUBLIC"],
)

